# Test local: 3 nodos C++ en localhost
cluster.nodes=cpp_a,cpp_b,cpp_c

node.cpp_a.host=127.0.0.1
node.cpp_a.port=9001

node.cpp_b.host=127.0.0.1
node.cpp_b.port=9002

node.cpp_c.host=127.0.0.1
node.cpp_c.port=9003
