# Test local del vigilante
cluster.nodes=cpp_a,cpp_b,cpp_c

cpp_a.host=127.0.0.1
cpp_a.port=9001

cpp_b.host=127.0.0.1
cpp_b.port=9002

cpp_c.host=127.0.0.1
cpp_c.port=9003

http.port=8888
refresh.interval.ms=3000
detections.dir=detecciones
