# Configuracion del Cliente Vigilante
cluster.nodes=java1,python1,cpp1

node.java1.host=192.168.1.10
node.java1.port=6001

node.python1.host=192.168.1.11
node.python1.port=6002

node.cpp1.host=192.168.1.12
node.cpp1.port=6003

http.port=8080
refresh.interval.ms=3000
detections.dir=detecciones
