# SOLO PARA PRUEBAS LOCALES: 3 nodos, todos en Java, todos en localhost,
# para validar la logica de eleccion de lider y replicacion de log ANTES
# de integrar los nodos reales de Python y C++.
#
# Uso (en 3 terminales distintas):
#   java -cp out cc4p1.raft.RaftNodeMain nodoA config/cluster-local-test.properties
#   java -cp out cc4p1.raft.RaftNodeMain nodoB config/cluster-local-test.properties
#   java -cp out cc4p1.raft.RaftNodeMain nodoC config/cluster-local-test.properties

cluster.nodes=nodoA,nodoB,nodoC

node.nodoA.host=127.0.0.1
node.nodoA.port=7001

node.nodoB.host=127.0.0.1
node.nodoB.port=7002

node.nodoC.host=127.0.0.1
node.nodoC.port=7003
