# Prueba con 2 laptops: java1+python1 en tu laptop, cpp1 en la del compañero
# CAMBIA las IPs por las reales que sacaste con ipconfig / hostname -I
cluster.nodes=java1,python1,cpp1

node.java1.host=192.168.1.15
node.java1.port=6001

node.python1.host=192.168.1.15
node.python1.port=6002

node.cpp1.host=192.168.1.20
node.cpp1.port=9001
